spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?characterEncoding=UTF-8
    username: postgres
    password: "test1234"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
